#!/bin/bash
# @Author: clsty <celestial.y@outlook.com>
# @Title: arCNiso publishiso: auto publish file.
# @URL: https://github.com/clsty/arCNiso
# @License: GNU GPL v3.0 License

function try { "$@" || sleep 0; }
set -e
cd $(dirname $0)

echo "Checking if every needed command is available..."
checkexist() {
	if command -v $1 >/dev/null 2>&1; then
		echo "Command $1 found."
	else
		echo "Error: Command $1 not found, aborting..."
		exit 1
	fi
}

for i in fd qbittorrent-nox transmission-create gh; do
	checkexist $i
done
echo "Great, every needed command is available."

./publishiso-1-release.sh $1
./publishiso-2-bt.sh
./publishiso-3-alist.sh
./publishiso-4-gh.sh
./publishiso-5-local.sh
